/**
 * Production dataset of 50 realistic Indian hotels for StayAdda AI.
 */
const sampleListings = [
    {
        title: "The Taj Mahal Palace & Tower",
        description: "Iconic luxury hotel overlooking the Gateway of India and the Arabian Sea. Featuring world-class dining, lavish suites, an expansive spa, and timeless colonial architecture.",
        image: { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80", filename: "listing_taj_mumbai" },
        price: 24000,
        location: "Apollo Bunder, Colaba",
        city: "Mumbai",
        state: "Maharashtra",
        country: "India",
        category: "Luxury",
        rating: 4.9,
        numReviews: 280,
        amenities: ["WiFi", "Pool", "AC", "Spa", "Ocean View", "Fine Dining", "Gym", "Valet Parking"],
        coordinates: { lat: 18.922, lng: 72.8332 },
        nearbyAttractions: [{ name: "Gateway of India", distance: "0.2 km" }, { name: "Marine Drive", distance: "2.5 km" }],
        travelType: ["Couples", "Luxury", "Business", "Family"],
        roomTypes: [
            { name: "Executive Suite Sea View", price: 24000, capacity: 2 },
            { name: "Grand Heritage Room", price: 38000, capacity: 3 }
        ],
        availableRooms: 6,
        bestSeason: ["October", "November", "December", "January", "February"]
    },
    {
        title: "Villa Calangute Beach Resort",
        description: "Stunning beachfront villa resort steps away from Calangute Beach in North Goa. Enjoy private plunge pools, lush tropical gardens, and vibrant beach shacks.",
        image: { url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80", filename: "listing_goa_villa" },
        price: 8500,
        location: "Calangute Beach Road",
        city: "Goa",
        state: "Goa",
        country: "India",
        category: "Beachfront",
        rating: 4.7,
        numReviews: 142,
        amenities: ["WiFi", "Pool", "AC", "Beach Access", "Bar", "Free Breakfast", "Parking"],
        coordinates: { lat: 15.5494, lng: 73.7535 },
        nearbyAttractions: [{ name: "Calangute Beach", distance: "0.1 km" }, { name: "Baga Beach", distance: "2.0 km" }],
        travelType: ["Friends", "Couples", "Solo"],
        roomTypes: [
            { name: "Beach View Cottage", price: 8500, capacity: 2 },
            { name: "Private Villa with Pool", price: 16000, capacity: 4 }
        ],
        availableRooms: 4,
        bestSeason: ["November", "December", "January", "February", "March"]
    },
    {
        title: "The Oberoi Udaivilas",
        description: "Set on the banks of Lake Pichola, offering grand domes, hand-painted corridors, private courtyard swimming pools, and majestic Rajasthani hospitality.",
        image: { url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80", filename: "listing_oberoi_udaipur" },
        price: 32000,
        location: "Haridasji Ki Magri",
        city: "Udaipur",
        state: "Rajasthan",
        country: "India",
        category: "Heritage",
        rating: 4.9,
        numReviews: 310,
        amenities: ["WiFi", "Pool", "AC", "Spa", "Lake View", "Heritage Architecture", "Fine Dining"],
        coordinates: { lat: 24.577, lng: 73.673 },
        nearbyAttractions: [{ name: "Lake Pichola", distance: "0.3 km" }, { name: "City Palace Udaipur", distance: "1.8 km" }],
        travelType: ["Couples", "Luxury", "Family"],
        roomTypes: [
            { name: "Premier Room Lake View", price: 32000, capacity: 2 },
            { name: "Luxury Suite with Private Pool", price: 55000, capacity: 3 }
        ],
        availableRooms: 3,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Rambagh Palace Jaipur",
        description: "Former residence of the Maharaja of Jaipur. Experience opulent royal suites, peacock-dotted gardens, fine dining in historic saloons, and traditional polo events.",
        image: { url: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80", filename: "listing_rambagh_jaipur" },
        price: 29000,
        location: "Bhawani Singh Road",
        city: "Jaipur",
        state: "Rajasthan",
        country: "India",
        category: "Heritage",
        rating: 4.8,
        numReviews: 195,
        amenities: ["WiFi", "Pool", "AC", "Royal Gardens", "Spa", "Fine Dining", "Valet Parking"],
        coordinates: { lat: 26.898, lng: 75.809 },
        nearbyAttractions: [{ name: "Hawa Mahal", distance: "4.0 km" }, { name: "City Palace Jaipur", distance: "4.5 km" }],
        travelType: ["Couples", "Luxury", "Family"],
        roomTypes: [
            { name: "Palace Room", price: 29000, capacity: 2 },
            { name: "Historical Suite", price: 48000, capacity: 3 }
        ],
        availableRooms: 5,
        bestSeason: ["October", "November", "December", "January", "February"]
    },
    {
        title: "Wildflower Hall, An Oberoi Resort",
        description: "Situated 8,250 feet above sea level in the Himalayas. Features heated outdoor infinity whirlpools, pine forest trails, and majestic mountain peak panoramas.",
        image: { url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80", filename: "listing_wildflower_shimla" },
        price: 21000,
        location: "Chharabra",
        city: "Shimla",
        state: "Himachal Pradesh",
        country: "India",
        category: "Mountain",
        rating: 4.9,
        numReviews: 230,
        amenities: ["WiFi", "Heated Pool", "Mountain View", "Spa", "Fireplace", "Trekking Trails", "Restaurant"],
        coordinates: { lat: 31.111, lng: 77.242 },
        nearbyAttractions: [{ name: "Kufri", distance: "5.0 km" }, { name: "The Ridge Shimla", distance: "12.0 km" }],
        travelType: ["Couples", "Family", "Solo"],
        roomTypes: [
            { name: "Deluxe Valley View Room", price: 21000, capacity: 2 },
            { name: "Premier Mountain Suite", price: 34000, capacity: 3 }
        ],
        availableRooms: 4,
        bestSeason: ["December", "January", "February", "April", "May", "June"]
    },
    {
        title: "Solang Valley Mountain Retreat",
        description: "Alpine-style timber chalet in Manali surrounded by snow-capped peaks and apple orchards. Perfect for adventure sports lovers and serene mountain getaways.",
        image: { url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80", filename: "listing_manali_retreat" },
        price: 6800,
        location: "Solang Valley Road",
        city: "Manali",
        state: "Himachal Pradesh",
        country: "India",
        category: "Mountain",
        rating: 4.6,
        numReviews: 115,
        amenities: ["WiFi", "AC", "Heating", "Mountain View", "Bonfire", "Free Breakfast", "Balcony"],
        coordinates: { lat: 32.316, lng: 77.157 },
        nearbyAttractions: [{ name: "Solang Ropeway", distance: "0.5 km" }, { name: "Rohtang Pass Gate", distance: "10.0 km" }],
        travelType: ["Friends", "Couples", "Solo"],
        roomTypes: [
            { name: "Pine Wood Deluxe Room", price: 6800, capacity: 2 },
            { name: "Attic Family Suite", price: 11500, capacity: 4 }
        ],
        availableRooms: 8,
        bestSeason: ["December", "January", "February", "May", "June"]
    },
    {
        title: "Kumarakom Lake Resort",
        description: "Heritage luxury resort on the banks of Vembanad Lake in Kerala backwaters. Features traditional Keralite architecture, meandering pool villas, and sunset cruises.",
        image: { url: "https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?auto=format&fit=crop&w=1200&q=80", filename: "listing_kerala_resort" },
        price: 18500,
        location: "Vembanad Lake Shore",
        city: "Kumarakom",
        state: "Kerala",
        country: "India",
        category: "Resort",
        rating: 4.8,
        numReviews: 178,
        amenities: ["WiFi", "Pool", "Lake View", "Ayurvedic Spa", "Houseboat Cruise", "Restaurant"],
        coordinates: { lat: 9.6175, lng: 76.4301 },
        nearbyAttractions: [{ name: "Kumarakom Bird Sanctuary", distance: "2.0 km" }, { name: "Vembanad Lake", distance: "0.0 km" }],
        travelType: ["Family", "Couples", "Luxury"],
        roomTypes: [
            { name: "Meandering Pool Villa", price: 18500, capacity: 2 },
            { name: "Heritage Lake View Cottage", price: 26000, capacity: 3 }
        ],
        availableRooms: 5,
        bestSeason: ["September", "October", "November", "December", "January", "February"]
    },
    {
        title: "BrijRama Palace Varanasi",
        description: "Heritage riverfront palace at Darbhanga Ghat on the sacred Ganges. Access via traditional wooden boat with morning yoga sessions and rooftop evening Aarti views.",
        image: { url: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=1200&q=80", filename: "listing_varanasi_palace" },
        price: 16000,
        location: "Darbhanga Ghat, Dashashwamedh",
        city: "Varanasi",
        state: "Uttar Pradesh",
        country: "India",
        category: "Heritage",
        rating: 4.7,
        numReviews: 162,
        amenities: ["WiFi", "Ganga River View", "Elevator", "Pure Veg Restaurant", "Yoga Deck", "Cultural Shows"],
        coordinates: { lat: 25.3045, lng: 83.0105 },
        nearbyAttractions: [{ name: "Dashashwamedh Ghat", distance: "0.4 km" }, { name: "Kashi Vishwanath Temple", distance: "0.8 km" }],
        travelType: ["Solo", "Family", "Couples"],
        roomTypes: [
            { name: "Varuna Suite Ganga View", price: 16000, capacity: 2 },
            { name: "Maharaja Suite", price: 28000, capacity: 3 }
        ],
        availableRooms: 4,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Ananda in the Himalayas",
        description: "World-famous holistic wellness retreat set in a 100-acre Maharaja estate near Rishikesh. Renowned for Ayurvedic therapies, Vedanta lectures, and yoga sanctuaries.",
        image: { url: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&w=1200&q=80", filename: "listing_ananda_rishikesh" },
        price: 35000,
        location: "The Palace Estate, Narendra Nagar",
        city: "Rishikesh",
        state: "Uttarakhand",
        country: "India",
        category: "Luxury",
        rating: 4.9,
        numReviews: 215,
        amenities: ["WiFi", "Ayurvedic Spa", "Yoga Pavilion", "Pool", "Organic Dining", "Golf Course"],
        coordinates: { lat: 30.133, lng: 78.298 },
        nearbyAttractions: [{ name: "Triveni Ghat", distance: "14.0 km" }, { name: "Lakshman Jhula", distance: "16.0 km" }],
        travelType: ["Solo", "Couples", "Luxury"],
        roomTypes: [
            { name: "Palace View Deluxe Room", price: 35000, capacity: 2 },
            { name: "Ananda Suite", price: 62000, capacity: 2 }
        ],
        availableRooms: 3,
        bestSeason: ["September", "October", "November", "March", "April", "May"]
    },
    {
        title: "Palais de Mahe - CGH Earth",
        description: "French colonial style boutique hotel in the heart of Pondicherry's French Quarter. Features grand high ceilings, courtyard pool, and yellow stucco verandas.",
        image: { url: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80", filename: "listing_pondicherry_palais" },
        price: 11000,
        location: "Bussy Street, White Town",
        city: "Pondicherry",
        state: "Puducherry",
        country: "India",
        category: "Boutique",
        rating: 4.7,
        numReviews: 128,
        amenities: ["WiFi", "Pool", "AC", "French Bistro", "Beach Promenade Access", "Massage Center"],
        coordinates: { lat: 11.9325, lng: 79.8335 },
        nearbyAttractions: [{ name: "Promenade Beach", distance: "0.2 km" }, { name: "Sri Aurobindo Ashram", distance: "0.6 km" }],
        travelType: ["Couples", "Solo", "Friends"],
        roomTypes: [
            { name: "Deluxe Colonial Room", price: 11000, capacity: 2 },
            { name: "Veranda Heritage Suite", price: 17500, capacity: 3 }
        ],
        availableRooms: 6,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Savoy - IHCL SeleQtions Ooty",
        description: "Charming Victorian-style English heritage hotel established in 1829. Features landscaped rose gardens, cozy fireplaces, high tea, and serene Nilgiri mountain views.",
        image: { url: "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=1200&q=80", filename: "listing_savoy_ooty" },
        price: 14500,
        location: "77 Sylks Road",
        city: "Ooty",
        state: "Tamil Nadu",
        country: "India",
        category: "Heritage",
        rating: 4.6,
        numReviews: 104,
        amenities: ["WiFi", "Fireplace", "Garden View", "High Tea Lounge", "Spa", "Restaurant", "Bar"],
        coordinates: { lat: 11.4102, lng: 76.695 },
        nearbyAttractions: [{ name: "Ooty Lake", distance: "1.5 km" }, { name: "Government Botanical Garden", distance: "2.5 km" }],
        travelType: ["Family", "Couples"],
        roomTypes: [
            { name: "Rose Garden Suite", price: 14500, capacity: 2 },
            { name: "Victorian Cottage Room", price: 21000, capacity: 3 }
        ],
        availableRooms: 5,
        bestSeason: ["April", "May", "June", "September", "October", "November"]
    },
    {
        title: "The Windflower Resort & Spa Coorg",
        description: "Spread across a 25-acre coffee plantation in Kodagu. Features open-air baths, private infinity pools, coffee tasting sessions, and soothing forest walks.",
        image: { url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80", filename: "listing_coorg_resort" },
        price: 9800,
        location: "Kedakal Village, Suntikoppa",
        city: "Coorg",
        state: "Karnataka",
        country: "India",
        category: "Resort",
        rating: 4.7,
        numReviews: 165,
        amenities: ["WiFi", "Pool", "Coffee Plantation Tour", "Spa", "Multi-Cuisine Restaurant", "Games Room"],
        coordinates: { lat: 12.4485, lng: 75.811 },
        nearbyAttractions: [{ name: "Abbey Falls", distance: "8.0 km" }, { name: "Raja's Seat", distance: "10.0 km" }],
        travelType: ["Family", "Couples", "Friends"],
        roomTypes: [
            { name: "Plantation Villa", price: 9800, capacity: 2 },
            { name: "Suite with Open Air Bath", price: 15000, capacity: 3 }
        ],
        availableRooms: 7,
        bestSeason: ["September", "October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Glenburn Tea Estate",
        description: "Boutique plantation retreat overlooking Mount Kanchenjunga. Features colonial bungalow suites, tea garden walks, river picnics, and candlelit dinners.",
        image: { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80", filename: "listing_darjeeling_glenburn" },
        price: 26000,
        location: "Glenburn Tea Estate",
        city: "Darjeeling",
        state: "West Bengal",
        country: "India",
        category: "Boutique",
        rating: 4.9,
        numReviews: 88,
        amenities: ["WiFi", "Kanchenjunga View", "Tea Tasting", "All-Inclusive Dining", "Guided Hikes"],
        coordinates: { lat: 27.085, lng: 88.315 },
        nearbyAttractions: [{ name: "Tiger Hill", distance: "18.0 km" }, { name: "Darjeeling Mall Road", distance: "15.0 km" }],
        travelType: ["Couples", "Luxury", "Solo"],
        roomTypes: [
            { name: "Kanchenjunga Suite", price: 26000, capacity: 2 },
            { name: "Planter's Suite", price: 35000, capacity: 2 }
        ],
        availableRooms: 4,
        bestSeason: ["March", "April", "May", "October", "November", "December"]
    },
    {
        title: "The Lalit Grand Palace Srinagar",
        description: "Designed by Maharajah Pratap Singh in 1910 overlooking Dal Lake. Surrounded by majestic Chinar trees, sprawling manicured lawns, and snow-topped mountain peaks.",
        image: { url: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80", filename: "listing_srinagar_lalit" },
        price: 22500,
        location: "Gupkar Road",
        city: "Srinagar",
        state: "Jammu and Kashmir",
        country: "India",
        category: "Heritage",
        rating: 4.8,
        numReviews: 210,
        amenities: ["WiFi", "Dal Lake View", "Indoor Heated Pool", "Chinar Gardens", "Shikara Booking", "Bar"],
        coordinates: { lat: 34.08, lng: 74.862 },
        nearbyAttractions: [{ name: "Dal Lake", distance: "0.5 km" }, { name: "Nishat Bagh", distance: "5.0 km" }],
        travelType: ["Family", "Couples", "Luxury"],
        roomTypes: [
            { name: "Palace Deluxe Lake View", price: 22500, capacity: 2 },
            { name: "Maharajah Suite", price: 42000, capacity: 3 }
        ],
        availableRooms: 5,
        bestSeason: ["April", "May", "June", "July", "August", "September", "October"]
    },
    {
        title: "JW Marriott Mussoorie Walnut Grove Resort",
        description: "Nestled amidst the lush green Garhwal mountain ranges. Offering high-altitude heated pools, bowling alleys, cedar forest trails, and signature spa treatments.",
        image: { url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80", filename: "listing_mussoorie_marriott" },
        price: 19500,
        location: "Village Siya, Kempty Fall Road",
        city: "Mussoorie",
        state: "Uttarakhand",
        country: "India",
        category: "Luxury",
        rating: 4.8,
        numReviews: 245,
        amenities: ["WiFi", "Heated Pool", "Valley View", "Spa", "Bowling Alley", "Kids Club", "Fine Dining"],
        coordinates: { lat: 30.478, lng: 78.041 },
        nearbyAttractions: [{ name: "Kempty Falls", distance: "3.0 km" }, { name: "Mall Road Mussoorie", distance: "6.0 km" }],
        travelType: ["Family", "Couples", "Friends"],
        roomTypes: [
            { name: "Valley View Deluxe Room", price: 19500, capacity: 2 },
            { name: "Executive Cedar Suite", price: 32000, capacity: 4 }
        ],
        availableRooms: 6,
        bestSeason: ["April", "May", "June", "October", "November", "December"]
    },
    {
        title: "Umaid Bhawan Palace Jodhpur",
        description: "One of the world's largest private residences. Built with golden-yellow sandstone, featuring subterranean Zodiac pool, vintage car museum, and royal dining.",
        image: { url: "https://images.unsplash.com/photo-1590073242678-70ee3fc28e8e?auto=format&fit=crop&w=1200&q=80", filename: "listing_umaid_jodhpur" },
        price: 42000,
        location: "Circuit House Road",
        city: "Jodhpur",
        state: "Rajasthan",
        country: "India",
        category: "Heritage",
        rating: 4.9,
        numReviews: 340,
        amenities: ["WiFi", "Zodiac Pool", "Royal Museum", "Spa", "Fine Dining", "Peacock Gardens"],
        coordinates: { lat: 26.281, lng: 73.048 },
        nearbyAttractions: [{ name: "Mehrangarh Fort", distance: "5.0 km" }, { name: "Jaswant Thada", distance: "5.5 km" }],
        travelType: ["Couples", "Luxury", "Family"],
        roomTypes: [
            { name: "Palace Room Golden View", price: 42000, capacity: 2 },
            { name: "Royal Suite", price: 75000, capacity: 3 }
        ],
        availableRooms: 2,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Suryagarh Jaisalmer",
        description: "A fortress palace standing proud in the Thar Desert. Features traditional courtyard folk dance performances, camel safaris, starlit dinners, and desert spa rituals.",
        image: { url: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80", filename: "listing_suryagarh_jaisalmer" },
        price: 21000,
        location: "Kahala Phata, Sam Road",
        city: "Jaisalmer",
        state: "Rajasthan",
        country: "India",
        category: "Heritage",
        rating: 4.8,
        numReviews: 189,
        amenities: ["WiFi", "Indoor Pool", "Desert Safari", "Folk Music", "Spa", "Restro Bar"],
        coordinates: { lat: 26.905, lng: 70.812 },
        nearbyAttractions: [{ name: "Jaisalmer Fort", distance: "15.0 km" }, { name: "Sam Sand Dunes", distance: "20.0 km" }],
        travelType: ["Couples", "Family", "Friends"],
        roomTypes: [
            { name: "Palace Room Desert View", price: 21000, capacity: 2 },
            { name: "Thar Heritage Suite", price: 36000, capacity: 3 }
        ],
        availableRooms: 4,
        bestSeason: ["October", "November", "December", "January", "February"]
    },
    {
        title: "The Leela Palace New Delhi",
        description: "Situated in Chanakyapuri diplomatic enclave. Offers rooftop temperature-controlled pool, Michelin-star dining options, opulent crystal chandeliers, and lavish butler service.",
        image: { url: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1200&q=80", filename: "listing_leela_delhi" },
        price: 25000,
        location: "Diplomatic Enclave, Chanakyapuri",
        city: "New Delhi",
        state: "Delhi",
        country: "India",
        category: "Luxury",
        rating: 4.9,
        numReviews: 290,
        amenities: ["WiFi", "Rooftop Pool", "AC", "Butler Service", "Spa", "Michelin Dining", "Gym"],
        coordinates: { lat: 28.583, lng: 77.186 },
        nearbyAttractions: [{ name: "India Gate", distance: "5.0 km" }, { name: "Rashtrapati Bhavan", distance: "3.5 km" }],
        travelType: ["Business", "Luxury", "Couples"],
        roomTypes: [
            { name: "Grand Deluxe Room", price: 25000, capacity: 2 },
            { name: "Royal Executive Suite", price: 45000, capacity: 3 }
        ],
        availableRooms: 7,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "ITC Grand Chola Chennai",
        description: "Tribute to the Chola Dynasty's architectural grandeur. Featuring 600 rooms, 10 dining destinations, rooftop pools, and sustainable LEED Platinum luxury rating.",
        image: { url: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80", filename: "listing_itc_chennai" },
        price: 15500,
        location: "No. 63, Mount Road, Guindy",
        city: "Chennai",
        state: "Tamil Nadu",
        country: "India",
        category: "Luxury",
        rating: 4.7,
        numReviews: 205,
        amenities: ["WiFi", "3 Pools", "Kaya Kalp Spa", "10 Restaurants", "Executive Lounge", "Gym"],
        coordinates: { lat: 13.0102, lng: 80.2155 },
        nearbyAttractions: [{ name: "Guindy National Park", distance: "1.0 km" }, { name: "Marina Beach", distance: "9.0 km" }],
        travelType: ["Business", "Family", "Luxury"],
        roomTypes: [
            { name: "Executive Club Room", price: 15500, capacity: 2 },
            { name: "Chola Grand Suite", price: 28000, capacity: 3 }
        ],
        availableRooms: 10,
        bestSeason: ["November", "December", "January", "February"]
    },
    {
        title: "The Oberoi Grand Kolkata",
        description: "Known fondly as the 'Grand Dame of Kolkata'. Located on Jawaharlal Nehru Road, offering Victorian elegance, palm-fringed swimming pool, and heritage high tea.",
        image: { url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80", filename: "listing_oberoi_kolkata" },
        price: 13500,
        location: "15 Jawaharlal Nehru Road",
        city: "Kolkata",
        state: "West Bengal",
        country: "India",
        category: "Heritage",
        rating: 4.7,
        numReviews: 175,
        amenities: ["WiFi", "Pool", "Colonial Bar", "Spa", "Fine Dining", "Gym", "Concierge"],
        coordinates: { lat: 22.56, lng: 88.351 },
        nearbyAttractions: [{ name: "Victoria Memorial", distance: "2.0 km" }, { name: "New Market", distance: "0.3 km" }],
        travelType: ["Business", "Family", "Solo"],
        roomTypes: [
            { name: "Premier Colonial Room", price: 13500, capacity: 2 },
            { name: "Executive Heritage Suite", price: 23000, capacity: 3 }
        ],
        availableRooms: 8,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Marari Beach Resort - CGH Earth",
        description: "Eco-friendly coconut grove beach resort in Mararikulam near Alleppey. Offers quiet sandy beaches, traditional thatched cottages, and organic farm-to-table cuisine.",
        image: { url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80", filename: "listing_marari_beach" },
        price: 13000,
        location: "Mararikulam North",
        city: "Alleppey",
        state: "Kerala",
        country: "India",
        category: "Beachfront",
        rating: 4.8,
        numReviews: 140,
        amenities: ["WiFi", "Pool", "Beach Access", "Ayurveda Wellness", "Organic Restaurant", "Bicycle Rental"],
        coordinates: { lat: 9.601, lng: 76.297 },
        nearbyAttractions: [{ name: "Marari Beach", distance: "0.1 km" }, { name: "Alleppey Backwaters", distance: "14.0 km" }],
        travelType: ["Couples", "Family", "Solo"],
        roomTypes: [
            { name: "Garden Villa Cottage", price: 13000, capacity: 2 },
            { name: "Pool Villa Cottage", price: 21000, capacity: 3 }
        ],
        availableRooms: 6,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Evolve Back Kabini",
        description: "Inspired by tribal Kadu Kuruba village architecture on the banks of Kabini River. Offers jeep safaris into Nagarhole Tiger Reserve, coracle boat rides, and infinity pool.",
        image: { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80", filename: "listing_evolve_kabini" },
        price: 27000,
        location: "Bheeramballi Village, H D Kote Taluk",
        city: "Kabini",
        state: "Karnataka",
        country: "India",
        category: "Resort",
        rating: 4.9,
        numReviews: 190,
        amenities: ["WiFi", "River Pool", "Wildlife Safari", "Ayurvedic Spa", "Coracle Ride", "Restaurant"],
        coordinates: { lat: 11.918, lng: 76.248 },
        nearbyAttractions: [{ name: "Nagarhole Tiger Reserve", distance: "5.0 km" }, { name: "Kabini Dam", distance: "12.0 km" }],
        travelType: ["Family", "Couples", "Luxury"],
        roomTypes: [
            { name: "Safari Hut with Jacuzzi", price: 27000, capacity: 2 },
            { name: "Pool Reserve Villa", price: 42000, capacity: 4 }
        ],
        availableRooms: 3,
        bestSeason: ["October", "November", "December", "January", "February", "March", "April", "May"]
    },
    {
        title: "The Serai Chikmagalur",
        description: "Set amidst sprawling coffee plantations in the Baba Budangiri hills. Private villas with personal pools, coffee aromatherapy spa sessions, and guided estate walks.",
        image: { url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80", filename: "listing_serai_chikmagalur" },
        price: 17500,
        location: "Mugthihalli Post, KM Road",
        city: "Chikmagalur",
        state: "Karnataka",
        country: "India",
        category: "Resort",
        rating: 4.7,
        numReviews: 155,
        amenities: ["WiFi", "Private Pool", "Coffee Tour", "Oma Spa", "Gym", "Cycling Tracks", "Fine Dining"],
        coordinates: { lat: 13.315, lng: 75.775 },
        nearbyAttractions: [{ name: "Mullayanagiri Peak", distance: "15.0 km" }, { name: "Baba Budangiri", distance: "22.0 km" }],
        travelType: ["Couples", "Family", "Friends"],
        roomTypes: [
            { name: "Estate Villa with Pool", price: 17500, capacity: 2 },
            { name: "Estate Terrace Suite", price: 24000, capacity: 3 }
        ],
        availableRooms: 5,
        bestSeason: ["September", "October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Sterling Wayanad Resort",
        description: "Picturesque valley resort nestled between pepper plantations and paddy fields in Wayanad. Features bird watching decks, tribal art workshops, and outdoor pools.",
        image: { url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80", filename: "listing_sterling_wayanad" },
        price: 6500,
        location: "Vultan Estate, Kidanganad",
        city: "Wayanad",
        state: "Kerala",
        country: "India",
        category: "Resort",
        rating: 4.5,
        numReviews: 98,
        amenities: ["WiFi", "Pool", "Paddy Field View", "Restaurant", "Campfire", "Indoor Games"],
        coordinates: { lat: 11.642, lng: 76.241 },
        nearbyAttractions: [{ name: "Muthanga Wildlife Sanctuary", distance: "6.0 km" }, { name: "Edakkal Caves", distance: "18.0 km" }],
        travelType: ["Family", "Friends", "Budget"],
        roomTypes: [
            { name: "Classic Valley Room", price: 6500, capacity: 2 },
            { name: "Privilege Cottage", price: 10500, capacity: 3 }
        ],
        availableRooms: 9,
        bestSeason: ["October", "November", "December", "January", "February", "March", "May"]
    },
    {
        title: "Carlton Hotel Kodaikanal",
        description: "The only 5-star heritage hotel sitting on the edge of Kodai Lake. Offers private boat rides, golf course access, colonial fireplace parlors, and misty mountain views.",
        image: { url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80", filename: "listing_carlton_kodai" },
        price: 12500,
        location: "Lake Road",
        city: "Kodaikanal",
        state: "Tamil Nadu",
        country: "India",
        category: "Heritage",
        rating: 4.6,
        numReviews: 135,
        amenities: ["WiFi", "Lake View", "Fireplace", "Pedal Boating", "Gym", "Spa", "Terrace Grill"],
        coordinates: { lat: 10.234, lng: 77.489 },
        nearbyAttractions: [{ name: "Kodaikanal Lake", distance: "0.1 km" }, { name: "Coaker's Walk", distance: "1.0 km" }],
        travelType: ["Family", "Couples"],
        roomTypes: [
            { name: "Deluxe Lake View Room", price: 12500, capacity: 2 },
            { name: "Heritage Cottage", price: 19000, capacity: 3 }
        ],
        availableRooms: 6,
        bestSeason: ["April", "May", "June", "September", "October", "November"]
    },
    {
        title: "The Machan Lonavala",
        description: "Exclusive eco-resort with treehouses rising 30 to 45 feet above the canopy in the Western Ghats. Powered by solar and wind energy for total forest immersion.",
        image: { url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80", filename: "listing_machan_lonavala" },
        price: 14000,
        location: "Private Road, Atvan",
        city: "Lonavala",
        state: "Maharashtra",
        country: "India",
        category: "Boutique",
        rating: 4.8,
        numReviews: 160,
        amenities: ["Treehouse Stay", "Forest View", "Open Sky Bath", "Buffet Dining", "Stargazing Deck"],
        coordinates: { lat: 18.685, lng: 73.442 },
        nearbyAttractions: [{ name: "Tiger's Point", distance: "8.0 km" }, { name: "Bhushi Dam", distance: "10.0 km" }],
        travelType: ["Couples", "Solo", "Friends"],
        roomTypes: [
            { name: "Canopy Machan Treehouse", price: 14000, capacity: 2 },
            { name: "Heritage Starlight Machan", price: 22000, capacity: 4 }
        ],
        availableRooms: 4,
        bestSeason: ["July", "August", "September", "October", "November", "December"]
    },
    {
        title: "Welcomhotel by ITC Hotels Shimla",
        description: "Perched atop a quiet hill in Mashobra. Offers breathtaking views of dense pine forests, apple orchards, solar heated glasshouses, and fine Himachali dining.",
        image: { url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80", filename: "listing_welcom_shimla" },
        price: 11500,
        location: "Mashobra-Naldehra Road",
        city: "Shimla",
        state: "Himachal Pradesh",
        country: "India",
        category: "Mountain",
        rating: 4.7,
        numReviews: 110,
        amenities: ["WiFi", "Mountain View", "Spa", "Bar", "Himachali Cuisine", "Heated Rooms"],
        coordinates: { lat: 31.135, lng: 77.228 },
        nearbyAttractions: [{ name: "Naldehra Golf Course", distance: "6.0 km" }, { name: "Shimla Mall Road", distance: "10.0 km" }],
        travelType: ["Couples", "Family"],
        roomTypes: [
            { name: "Pine View Room", price: 11500, capacity: 2 },
            { name: "Valley Suite", price: 18000, capacity: 3 }
        ],
        availableRooms: 7,
        bestSeason: ["December", "January", "February", "April", "May", "June"]
    },
    {
        title: "Mayfair Spa Resort & Casino Gangtok",
        description: "Monastery-themed luxury resort nestled in the eastern Himalayan valley. Features Sikkim's finest casino, monastic architecture, and pampering spa rituals.",
        image: { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80", filename: "listing_mayfair_gangtok" },
        price: 13500,
        location: "Lower Samdur Block, Ranipool",
        city: "Gangtok",
        state: "Sikkim",
        country: "India",
        category: "Luxury",
        rating: 4.8,
        numReviews: 148,
        amenities: ["WiFi", "Casino", "Pool", "Himalayan View", "Spa", "Multi-Cuisine Restaurant", "Bar"],
        coordinates: { lat: 27.28, lng: 88.588 },
        nearbyAttractions: [{ name: "Rumtek Monastery", distance: "8.0 km" }, { name: "MG Marg Gangtok", distance: "10.0 km" }],
        travelType: ["Couples", "Friends", "Luxury"],
        roomTypes: [
            { name: "Grand Deluxe Villa", price: 13500, capacity: 2 },
            { name: "Imperial Family Cottage", price: 21000, capacity: 4 }
        ],
        availableRooms: 5,
        bestSeason: ["March", "April", "May", "October", "November", "December"]
    },
    {
        title: "Radisson Blu Resort Temple Bay Mamallapuram",
        description: "Expansive 44-acre beach resort on the Coromandel Coast. Boasts a massive 27,000 sq ft meandering pool, beach chalets, and proximity to UNESCO shore temples.",
        image: { url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80", filename: "listing_radisson_mahabs" },
        price: 12000,
        location: "57 Covelong Road",
        city: "Mahabalipuram",
        state: "Tamil Nadu",
        country: "India",
        category: "Beachfront",
        rating: 4.6,
        numReviews: 220,
        amenities: ["WiFi", "27,000 sqft Pool", "Beach Access", "Spa", "ATV Rides", "Seafood Restaurant"],
        coordinates: { lat: 12.624, lng: 80.198 },
        nearbyAttractions: [{ name: "Shore Temple", distance: "1.0 km" }, { name: "Arjuna's Penance", distance: "0.8 km" }],
        travelType: ["Family", "Friends", "Couples"],
        roomTypes: [
            { name: "Chalet Sea View", price: 12000, capacity: 2 },
            { name: "Pool Villa", price: 19500, capacity: 3 }
        ],
        availableRooms: 8,
        bestSeason: ["November", "December", "January", "February", "March"]
    },
    {
        title: "Grand Mercure Mysuru",
        description: "Situated in the historic royal city of Mysore near Sayyaji Rao Road. Features rooftop swimming pool, authentic Silk & Spice restaurant, and heritage tours.",
        image: { url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80", filename: "listing_mercure_mysore" },
        price: 7200,
        location: "Nelson Mandela Circle, Sayyaji Rao Road",
        city: "Mysuru",
        state: "Karnataka",
        country: "India",
        category: "Boutique",
        rating: 4.5,
        numReviews: 112,
        amenities: ["WiFi", "Rooftop Pool", "AC", "Fitness Center", "Restaurant", "Free Parking"],
        coordinates: { lat: 12.325, lng: 76.645 },
        nearbyAttractions: [{ name: "Mysore Palace", distance: "2.5 km" }, { name: "Chamundi Hill", distance: "11.0 km" }],
        travelType: ["Family", "Business", "Solo"],
        roomTypes: [
            { name: "Deluxe Queen Room", price: 7200, capacity: 2 },
            { name: "Executive Suite", price: 11800, capacity: 3 }
        ],
        availableRooms: 9,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "The Oberoi Amarvilas Agra",
        description: "Located just 600 meters from the Taj Mahal. Every single room offers unobstructed views of the monument of love, with reflection pools and Mughal lawn gardens.",
        image: { url: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?auto=format&fit=crop&w=1200&q=80", filename: "listing_amarvilas_agra" },
        price: 38000,
        location: "Taj East Gate Road",
        city: "Agra",
        state: "Uttar Pradesh",
        country: "India",
        category: "Luxury",
        rating: 4.9,
        numReviews: 325,
        amenities: ["WiFi", "Unobstructed Taj Mahal View", "Pool", "Mughal Spa", "Fine Dining", "Golf Cart Transit"],
        coordinates: { lat: 27.168, lng: 78.048 },
        nearbyAttractions: [{ name: "Taj Mahal", distance: "0.6 km" }, { name: "Agra Fort", distance: "3.2 km" }],
        travelType: ["Couples", "Luxury", "Family"],
        roomTypes: [
            { name: "Premier Room Taj Mahal View", price: 38000, capacity: 2 },
            { name: "Luxury Suite Taj View", price: 65000, capacity: 3 }
        ],
        availableRooms: 3,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Alila Diwa Goa",
        description: "Set amid serene paddy fields in Majorda, South Goa. Features an iconic infinity pool merging into green rice terraces, open-air bath spaces, and private beach shuttle.",
        image: { url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80", filename: "listing_alila_goa" },
        price: 15000,
        location: "48/10 Adao Waddo, Majorda",
        city: "Goa",
        state: "Goa",
        country: "India",
        category: "Resort",
        rating: 4.8,
        numReviews: 195,
        amenities: ["WiFi", "Infinity Pool", "Paddy Field View", "Spa", "Beach Shuttle", "Cocktail Lounge"],
        coordinates: { lat: 15.312, lng: 73.905 },
        nearbyAttractions: [{ name: "Majorda Beach", distance: "0.8 km" }, { name: "Colva Beach", distance: "5.0 km" }],
        travelType: ["Couples", "Family", "Luxury"],
        roomTypes: [
            { name: "Terrace Room Paddy View", price: 15000, capacity: 2 },
            { name: "Diwa Club Villa", price: 24000, capacity: 3 }
        ],
        availableRooms: 6,
        bestSeason: ["November", "December", "January", "February", "March"]
    },
    {
        title: "Taj Lake Palace Udaipur",
        description: "18th-century white marble floating palace in the middle of Lake Pichola. Accessible exclusively by private boat, offering butler service and historic royal suites.",
        image: { url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80", filename: "listing_taj_lakepalace" },
        price: 45000,
        location: "Pichola",
        city: "Udaipur",
        state: "Rajasthan",
        country: "India",
        category: "Heritage",
        rating: 4.9,
        numReviews: 360,
        amenities: ["WiFi", "Floating Boat Arrival", "Lake View", "Jharokha Dining", "Jiva Spa", "Royal Butler"],
        coordinates: { lat: 24.575, lng: 73.68 },
        nearbyAttractions: [{ name: "City Palace Udaipur", distance: "0.5 km" }, { name: "Jag Mandir", distance: "0.8 km" }],
        travelType: ["Couples", "Luxury"],
        roomTypes: [
            { name: "Palace Room Lake View", price: 45000, capacity: 2 },
            { name: "Grand Royal Suite", price: 85000, capacity: 3 }
        ],
        availableRooms: 2,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Fateh Prakash Palace",
        description: "Situated inside the City Palace Complex Udaipur. Houses priceless crystal gallery collections, grand durbar halls, and private lakefront balconies.",
        image: { url: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80", filename: "listing_fateh_prakash" },
        price: 18000,
        location: "The City Palace Complex",
        city: "Udaipur",
        state: "Rajasthan",
        country: "India",
        category: "Heritage",
        rating: 4.7,
        numReviews: 140,
        amenities: ["WiFi", "Pool", "City Palace Access", "Lake View", "Crystal Gallery", "Restaurant"],
        coordinates: { lat: 24.576, lng: 73.683 },
        nearbyAttractions: [{ name: "City Palace Museum", distance: "0.1 km" }, { name: "Jagdish Temple", distance: "0.4 km" }],
        travelType: ["Family", "Couples"],
        roomTypes: [
            { name: "Dovecote Deluxe Room", price: 18000, capacity: 2 },
            { name: "Grand Heritage Lake Suite", price: 29000, capacity: 3 }
        ],
        availableRooms: 5,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Ahuja Residences Golf Course Road Gurgaon",
        description: "Modern luxury serviced apartments in Gurgaon corporate hub. Features high-speed Wi-Fi, fully equipped modular kitchenettes, fitness center, and express breakfast.",
        image: { url: "https://images.unsplash.com/photo-1567684014761-b65e2e59b9eb?auto=format&fit=crop&w=1200&q=80", filename: "listing_gurgaon_ahuja" },
        price: 5500,
        location: "Sector 54, Golf Course Road",
        city: "Gurugram",
        state: "Haryana",
        country: "India",
        category: "Budget",
        rating: 4.4,
        numReviews: 85,
        amenities: ["WiFi", "AC", "Kitchenette", "Gym", "Free Breakfast", "Work Desk", "24h Security"],
        coordinates: { lat: 28.435, lng: 77.105 },
        nearbyAttractions: [{ name: "Cyber Hub Gurgaon", distance: "4.5 km" }, { name: "One Horizon Center", distance: "1.0 km" }],
        travelType: ["Business", "Solo"],
        roomTypes: [
            { name: "Studio Apartment", price: 5500, capacity: 2 },
            { name: "One Bedroom Suite", price: 8200, capacity: 3 }
        ],
        availableRooms: 12,
        bestSeason: ["All Season"]
    },
    {
        title: "Niramaya Retreats Surya Samudra Kovalam",
        description: "Cliff-edge beach resort in Kovalam featuring traditional Keralite heritage wooden cottages. Known globally for authentic Ayurvedic healing treatments and ocean infinity pool.",
        image: { url: "https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?auto=format&fit=crop&w=1200&q=80", filename: "listing_niramaya_kovalam" },
        price: 21000,
        location: "Pulinkudi, Mullur",
        city: "Kovalam",
        state: "Kerala",
        country: "India",
        category: "Beachfront",
        rating: 4.8,
        numReviews: 165,
        amenities: ["WiFi", "Cliff Infinity Pool", "Ocean View", "Ayurvedic Center", "Private Beach Path", "Open Air Baths"],
        coordinates: { lat: 8.375, lng: 76.982 },
        nearbyAttractions: [{ name: "Kovalam Beach", distance: "3.5 km" }, { name: "Lighthouse Beach", distance: "4.0 km" }],
        travelType: ["Couples", "Luxury", "Solo"],
        roomTypes: [
            { name: "Rock Castle Heritage Cottage", price: 21000, capacity: 2 },
            { name: "Ocean Crest Villa", price: 34000, capacity: 3 }
        ],
        availableRooms: 4,
        bestSeason: ["September", "October", "November", "December", "January", "February", "March"]
    },
    {
        title: "The Heritage Village Resort & Spa Manesar",
        description: "Rajasthani haveli-style resort set amidst 12 acres of lush green gardens near Delhi-NCR. Offers sprawling pools, wellness spa, and activity zones for family weekends.",
        image: { url: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80", filename: "listing_manesar_heritage" },
        price: 8900,
        location: "NH-8, Manesar",
        city: "Gurugram",
        state: "Haryana",
        country: "India",
        category: "Resort",
        rating: 4.5,
        numReviews: 130,
        amenities: ["WiFi", "Pool", "AC", "Spa", "Pet Friendly", "Barbecue", "Kids Play Area"],
        coordinates: { lat: 28.352, lng: 76.938 },
        nearbyAttractions: [{ name: "Sultanpur National Park", distance: "12.0 km" }],
        travelType: ["Family", "Friends", "Business"],
        roomTypes: [
            { name: "Heritage Superior Room", price: 8900, capacity: 2 },
            { name: "Haveli Suite", price: 14500, capacity: 4 }
        ],
        availableRooms: 8,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Taj Green Cove Resort & Spa Kovalam",
        description: "Situated on a hilltop overlooking Kovalam coastline and backwater lagoon. Features rustic thatched-roof villas, boat dining experience, and infinity pool.",
        image: { url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80", filename: "listing_taj_kovalam" },
        price: 17500,
        location: "G.V. Raja Salai",
        city: "Kovalam",
        state: "Kerala",
        country: "India",
        category: "Beachfront",
        rating: 4.7,
        numReviews: 185,
        amenities: ["WiFi", "Lagoon & Ocean View", "Pool", "Jiva Spa", "Bait Seafood Restaurant"],
        coordinates: { lat: 8.398, lng: 76.972 },
        nearbyAttractions: [{ name: "Samudra Beach", distance: "0.2 km" }, { name: "Trivandrum City", distance: "12.0 km" }],
        travelType: ["Couples", "Family", "Luxury"],
        roomTypes: [
            { name: "Superior Garden View Cottage", price: 17500, capacity: 2 },
            { name: "Deluxe Sea View Suite", price: 28000, capacity: 3 }
        ],
        availableRooms: 5,
        bestSeason: ["October", "November", "December", "January", "February"]
    },
    {
        title: "Samode Palace Jaipur",
        description: "400-year-old palace tucked away in the rugged Aravalli hills. World-renowned for its intricate Sheesh Mahal (Hall of Mirrors), marble pools, and royal banquets.",
        image: { url: "https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1200&q=80", filename: "listing_samode_jaipur" },
        price: 23000,
        location: "Samode Village, Tehsil Chomu",
        city: "Jaipur",
        state: "Rajasthan",
        country: "India",
        category: "Heritage",
        rating: 4.8,
        numReviews: 152,
        amenities: ["WiFi", "Infinity Rooftop Pool", "Sheesh Mahal Tour", "Royal Spa", "Fine Dining"],
        coordinates: { lat: 27.21, lng: 75.805 },
        nearbyAttractions: [{ name: "Samode Bagh", distance: "3.0 km" }, { name: "Jaipur City", distance: "42.0 km" }],
        travelType: ["Couples", "Luxury"],
        roomTypes: [
            { name: "Deluxe Palace Suite", price: 23000, capacity: 2 },
            { name: "Royal Royal Suite", price: 39000, capacity: 3 }
        ],
        availableRooms: 4,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "The Khyber Himalayan Resort & Spa Gulmarg",
        description: "8,200 feet up in the Himalayas, footsteps away from the Gulmarg Gondola. Offers indoor heated glass pool with views of Apharwat mountain peak, ski storage, and spa.",
        image: { url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80", filename: "listing_khyber_gulmarg" },
        price: 28000,
        location: "Apharwat Peak Road",
        city: "Gulmarg",
        state: "Jammu and Kashmir",
        country: "India",
        category: "Mountain",
        rating: 4.9,
        numReviews: 275,
        amenities: ["WiFi", "Ski-in Ski-out Access", "Heated Pool", "Apharwat Peak View", "L'Occitane Spa"],
        coordinates: { lat: 34.048, lng: 74.382 },
        nearbyAttractions: [{ name: "Gulmarg Gondola", distance: "0.2 km" }, { name: "Golf Course Gulmarg", distance: "1.0 km" }],
        travelType: ["Couples", "Family", "Luxury", "Solo"],
        roomTypes: [
            { name: "Premier Snow View Room", price: 28000, capacity: 2 },
            { name: "Luxury Cottage Suite", price: 48000, capacity: 4 }
        ],
        availableRooms: 3,
        bestSeason: ["December", "January", "February", "March", "April", "May"]
    },
    {
        title: "W Goa - Vagator Beach",
        description: "Trendy luxury lifestyle resort located at Vagator Beach beneath Chapora Fort. Famous for Rockpool sunset parties, modern bold decor, and vibrant nightlife access.",
        image: { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80", filename: "listing_w_goa" },
        price: 19000,
        location: "Vagator Beach, Bardez",
        city: "Goa",
        state: "Goa",
        country: "India",
        category: "Beachfront",
        rating: 4.7,
        numReviews: 235,
        amenities: ["WiFi", "Rockpool Lounge", "WET Outdoor Pool", "AWAY Spa", "Pet Friendly", "Bar"],
        coordinates: { lat: 15.602, lng: 73.734 },
        nearbyAttractions: [{ name: "Chapora Fort", distance: "0.5 km" }, { name: "Vagator Beach", distance: "0.2 km" }],
        travelType: ["Friends", "Couples", "Luxury"],
        roomTypes: [
            { name: "Wonderful Room Garden View", price: 19000, capacity: 2 },
            { name: "Marvelous Villa with Plunge Pool", price: 38000, capacity: 3 }
        ],
        availableRooms: 5,
        bestSeason: ["November", "December", "January", "February", "March"]
    },
    {
        title: "Ahilya Fort Hotel Maheshwar",
        description: "Perched high above the Narmada River in a 250-year-old fort built by Maharani Ahilyabai Holkar. Peaceful organic gardens, heritage rooms, and sunset boat rides.",
        image: { url: "https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=1200&q=80", filename: "listing_ahilya_fort" },
        price: 18500,
        location: "Ahilya Fort, Labhani Para",
        city: "Maheshwar",
        state: "Madhya Pradesh",
        country: "India",
        category: "Heritage",
        rating: 4.8,
        numReviews: 92,
        amenities: ["WiFi", "Narmada River View", "Pool", "Organic Farm Dining", "Sunset Boat Trip"],
        coordinates: { lat: 22.176, lng: 75.582 },
        nearbyAttractions: [{ name: "Maheshwar Ghats", distance: "0.1 km" }, { name: "Narmada River", distance: "0.0 km" }],
        travelType: ["Solo", "Couples"],
        roomTypes: [
            { name: "Narmada View Heritage Room", price: 18500, capacity: 2 },
            { name: "Royal Fort Suite", price: 29000, capacity: 3 }
        ],
        availableRooms: 4,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "RISE Rishikesh Beach Resort",
        description: "Rishikesh riverside eco-resort on the quiet banks of the Ganges in Shivpuri. Ideal for white water rafting enthusiasts, cliff jumping, yoga retreats, and evening campfires.",
        image: { url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80", filename: "listing_rishikesh_rise" },
        price: 5200,
        location: "Badrinath Road, Shivpuri",
        city: "Rishikesh",
        state: "Uttarakhand",
        country: "India",
        category: "Budget",
        rating: 4.4,
        numReviews: 105,
        amenities: ["WiFi", "River Beach Access", "White Water Rafting", "Bonfire", "Pure Veg Restaurant"],
        coordinates: { lat: 30.138, lng: 78.385 },
        nearbyAttractions: [{ name: "Shivpuri Rafting Point", distance: "0.5 km" }, { name: "Ram Jhula", distance: "12.0 km" }],
        travelType: ["Friends", "Solo", "Budget"],
        roomTypes: [
            { name: "Riverside Alpine Tent", price: 5200, capacity: 2 },
            { name: "Cottage Room Ganges View", price: 7800, capacity: 3 }
        ],
        availableRooms: 10,
        bestSeason: ["September", "October", "November", "March", "April", "May"]
    },
    {
        title: "Vivanta Goa Panaji",
        description: "Stylish urban hotel in capital city Panaji overlooking Mandovi River and Altinho Hills. Quick access to offshore casinos, Latin Quarter Fontainhas, and dining.",
        image: { url: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80", filename: "listing_vivanta_panaji" },
        price: 9200,
        location: "Off D.B. Bandodkar Road, St. Inez",
        city: "Panaji",
        state: "Goa",
        country: "India",
        category: "Boutique",
        rating: 4.6,
        numReviews: 170,
        amenities: ["WiFi", "Rooftop Pool", "Mandovi River View", "Spa", "Latitude Restaurant", "Gym"],
        coordinates: { lat: 15.495, lng: 73.818 },
        nearbyAttractions: [{ name: "Fontainhas Latin Quarter", distance: "1.2 km" }, { name: "Casino Pride Jetty", distance: "1.5 km" }],
        travelType: ["Business", "Solo", "Couples"],
        roomTypes: [
            { name: "Superior Charm Room", price: 9200, capacity: 2 },
            { name: "Executive River View Suite", price: 15000, capacity: 3 }
        ],
        availableRooms: 8,
        bestSeason: ["All Season"]
    },
    {
        title: "Mayfair Hideaway Spa Resort Betul",
        description: "Situated where the Sal River meets the Arabian Sea in South Goa. Quiet secluded location with infinity pool along the river, spa, and private boat rides to the beach.",
        image: { url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80", filename: "listing_mayfair_betul" },
        price: 8800,
        location: "Rangali, Betul",
        city: "Goa",
        state: "Goa",
        country: "India",
        category: "Resort",
        rating: 4.5,
        numReviews: 115,
        amenities: ["WiFi", "River Infinity Pool", "Sea Confluence View", "Spa", "Boat Shuttle", "Pool Bar"],
        coordinates: { lat: 15.148, lng: 73.952 },
        nearbyAttractions: [{ name: "Betul Beach", distance: "0.5 km" }, { name: "Mobor Beach", distance: "2.0 km" }],
        travelType: ["Couples", "Family"],
        roomTypes: [
            { name: "Deluxe Pool View Room", price: 8800, capacity: 2 },
            { name: "River Facing Suite", price: 13500, capacity: 3 }
        ],
        availableRooms: 7,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Jehan Numa Palace Hotel Bhopal",
        description: "Built in 1890 during the rule of Nawab Sultan Jehan Begum. Blends British colonial, Italianate, and Classical Greek architecture with royal dining saloons.",
        image: { url: "https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1200&q=80", filename: "listing_jehan_numa" },
        price: 8200,
        location: "157 Shamla Hill",
        city: "Bhopal",
        state: "Madhya Pradesh",
        country: "India",
        category: "Heritage",
        rating: 4.6,
        numReviews: 124,
        amenities: ["WiFi", "Pool", "Heritage Courtyard", "Under The Mango Tree Restaurant", "Spa", "Gym"],
        coordinates: { lat: 23.242, lng: 77.391 },
        nearbyAttractions: [{ name: "Upper Lake Bhopal", distance: "1.0 km" }, { name: "Van Vihar National Park", distance: "2.5 km" }],
        travelType: ["Business", "Family", "Couples"],
        roomTypes: [
            { name: "Imperial Room", price: 8200, capacity: 2 },
            { name: "Begum Heritage Suite", price: 13800, capacity: 3 }
        ],
        availableRooms: 6,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Hyatt Regency Amritsar",
        description: "Luxury hotel providing complimentary shuttle service to the Golden Temple. Features Vitality vitality spa, outdoor pool, and authentic Punjabi dining at Thai Chi & Collage.",
        image: { url: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=1200&q=80", filename: "listing_hyatt_amritsar" },
        price: 7500,
        location: "MBM Farms, GT Road",
        city: "Amritsar",
        state: "Punjab",
        country: "India",
        category: "Luxury",
        rating: 4.6,
        numReviews: 180,
        amenities: ["WiFi", "Golden Temple Shuttle", "Pool", "Spa", "Punjabi Restaurant", "Free Parking"],
        coordinates: { lat: 31.628, lng: 74.908 },
        nearbyAttractions: [{ name: "Golden Temple (Harmandir Sahib)", distance: "4.5 km" }, { name: "Jallianwala Bagh", distance: "4.2 km" }],
        travelType: ["Family", "Solo", "Couples"],
        roomTypes: [
            { name: "King Room Pool View", price: 7500, capacity: 2 },
            { name: "Regency Suite", price: 12500, capacity: 3 }
        ],
        availableRooms: 9,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Tamara Coorg",
        description: "Exclusive luxury eco-resort spread over 180 acres of organic coffee, cardamom, and pepper plantations. Features wooden cottages on stilts with private jacuzzi.",
        image: { url: "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?auto=format&fit=crop&w=1200&q=80", filename: "listing_tamara_coorg" },
        price: 21500,
        location: "Kabbinakad Estate, Yavakapadi Village",
        city: "Coorg",
        state: "Karnataka",
        country: "India",
        category: "Luxury",
        rating: 4.9,
        numReviews: 205,
        amenities: ["WiFi", "Stilt Cottage", "Jacuzzi", "Coffee Plantation Trek", "Elevation Spa", "Fine Dining"],
        coordinates: { lat: 12.215, lng: 75.722 },
        nearbyAttractions: [{ name: "Tadiandamol Peak", distance: "4.0 km" }, { name: "Chelavara Falls", distance: "8.0 km" }],
        travelType: ["Couples", "Luxury"],
        roomTypes: [
            { name: "Luxury Cottage Jacuzzi View", price: 21500, capacity: 2 },
            { name: "Eden Lotus Suite", price: 34000, capacity: 3 }
        ],
        availableRooms: 4,
        bestSeason: ["September", "October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Spice Village Thekkady - CGH Earth",
        description: "Recreation of a native tribal village located on the mist-shrouded hills of Periyar Tiger Reserve. Built with elephant grass thatch roofs and spice garden pathways.",
        image: { url: "https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=1200&q=80", filename: "listing_spice_thekkady" },
        price: 11800,
        location: "KUMILY, Thekkady Road",
        city: "Thekkady",
        state: "Kerala",
        country: "India",
        category: "Resort",
        rating: 4.7,
        numReviews: 150,
        amenities: ["WiFi", "Periyar Wildlife Tour", "Pool", "Spice Garden Walk", "Organic Dining", "Ayurveda"],
        coordinates: { lat: 9.605, lng: 77.168 },
        nearbyAttractions: [{ name: "Periyar National Park", distance: "1.0 km" }, { name: "Elephant Junction", distance: "3.0 km" }],
        travelType: ["Family", "Couples", "Solo"],
        roomTypes: [
            { name: "Spice Garden Cottage", price: 11800, capacity: 2 },
            { name: "Villa Cottage with Private Orchard", price: 18500, capacity: 3 }
        ],
        availableRooms: 6,
        bestSeason: ["September", "October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Fortune Resort Grace Mussoorie",
        description: "Situated on Library End of Mall Road in Mussoorie. Offers cozy wooden rooms overlooking Doon Valley, terrace dining, and direct walking access to shopping streets.",
        image: { url: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?auto=format&fit=crop&w=1200&q=80", filename: "listing_fortune_mussoorie" },
        price: 7800,
        location: "Library Bazaar, Mall Road",
        city: "Mussoorie",
        state: "Uttarakhand",
        country: "India",
        category: "Mountain",
        rating: 4.5,
        numReviews: 132,
        amenities: ["WiFi", "Doon Valley View", "AC", "Heating", "Orchid Restaurant", "Bar", "Game Room"],
        coordinates: { lat: 30.457, lng: 78.065 },
        nearbyAttractions: [{ name: "Mussoorie Mall Road", distance: "0.1 km" }, { name: "Gun Hill Cable Car", distance: "1.5 km" }],
        travelType: ["Family", "Friends", "Budget"],
        roomTypes: [
            { name: "Valley View Deluxe Room", price: 7800, capacity: 2 },
            { name: "Grace Family Suite", price: 12800, capacity: 4 }
        ],
        availableRooms: 8,
        bestSeason: ["April", "May", "June", "October", "November", "December"]
    },
    {
        title: "The Riverfort Villa Alibaug",
        description: "Private luxury pool villa situated along the river inlet in Alibaug. Surrounded by coconut palm groves, outdoor lounge beds, BBQ pits, and quick beach access.",
        image: { url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80", filename: "listing_alibaug_villa" },
        price: 13800,
        location: "Varnoli, Mapgaon",
        city: "Alibaug",
        state: "Maharashtra",
        country: "India",
        category: "Villa",
        rating: 4.6,
        numReviews: 95,
        amenities: ["WiFi", "Private Pool", "AC", "Barbecue Pit", "Private Lawn", "Caretaker Service", "Parking"],
        coordinates: { lat: 18.665, lng: 72.882 },
        nearbyAttractions: [{ name: "Varsoli Beach", distance: "3.0 km" }, { name: "Alibaug Fort", distance: "4.5 km" }],
        travelType: ["Friends", "Family"],
        roomTypes: [
            { name: "3-BHK Private Villa", price: 13800, capacity: 6 },
            { name: "4-BHK Luxury Lawn Villa", price: 21000, capacity: 10 }
        ],
        availableRooms: 2,
        bestSeason: ["October", "November", "December", "January", "February", "March"]
    },
    {
        title: "Lemon Tree Premier Jaipur",
        description: "Centrally located near Nirwan Nagar, offering stylish contemporary rooms, Citrus Cafe multi-cuisine restaurant, Slounge bar, and outdoor rooftop swimming pool.",
        image: { url: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80", filename: "listing_lemontree_jaipur" },
        price: 4900,
        location: "Nirwan Marg, Bani Park",
        city: "Jaipur",
        state: "Rajasthan",
        country: "India",
        category: "Budget",
        rating: 4.4,
        numReviews: 140,
        amenities: ["WiFi", "Rooftop Pool", "AC", "Citrus Cafe", "Gym", "Valet Parking"],
        coordinates: { lat: 26.928, lng: 75.795 },
        nearbyAttractions: [{ name: "Jaipur Junction Railway Station", distance: "1.5 km" }, { name: "City Palace", distance: "4.0 km" }],
        travelType: ["Business", "Solo", "Budget"],
        roomTypes: [
            { name: "Superior Room", price: 4900, capacity: 2 },
            { name: "Executive Suite", price: 7900, capacity: 3 }
        ],
        availableRooms: 12,
        bestSeason: ["All Season"]
    },
    {
        title: "Regenta Resort Varca Beach Goa",
        description: "Situated 500 meters from white sandy Varca Beach in South Goa. Features lagoon swimming pool, palm shaded sun loungers, outdoor dining, and water sports booking.",
        image: { url: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=1200&q=80", filename: "listing_regenta_varca" },
        price: 6900,
        location: "Pedda, Varca",
        city: "Goa",
        state: "Goa",
        country: "India",
        category: "Beachfront",
        rating: 4.5,
        numReviews: 128,
        amenities: ["WiFi", "Lagoon Pool", "AC", "Varca Beach Access", "Pinxx Restaurant", "Bar"],
        coordinates: { lat: 15.221, lng: 73.921 },
        nearbyAttractions: [{ name: "Varca Beach", distance: "0.5 km" }, { name: "Benaulim Beach", distance: "3.5 km" }],
        travelType: ["Family", "Couples", "Friends"],
        roomTypes: [
            { name: "Pool View Deluxe Room", price: 6900, capacity: 2 },
            { name: "Executive Suite", price: 11000, capacity: 3 }
        ],
        availableRooms: 8,
        bestSeason: ["November", "December", "January", "February", "March"]
    },
    {
        title: "Della Resorts Lonavala",
        description: "India's premier adventure resort boasting over 50 extreme adventure activities including swoop swing and dirt biking, paired with 5-star luxury rooms and fine dining.",
        image: { url: "https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=1200&q=80", filename: "listing_della_lonavala" },
        price: 16500,
        location: "Kune Village, Khandala",
        city: "Lonavala",
        state: "Maharashtra",
        country: "India",
        category: "Luxury",
        rating: 4.7,
        numReviews: 260,
        amenities: ["WiFi", "Adventure Park", "Pool", "24h Coffee Shop", "Spa", "Pet Friendly", "Bar"],
        coordinates: { lat: 18.762, lng: 73.398 },
        nearbyAttractions: [{ name: "Khandala Sunset Point", distance: "2.0 km" }, { name: "Lonavala Lake", distance: "5.0 km" }],
        travelType: ["Friends", "Family", "Luxury"],
        roomTypes: [
            { name: "Luxury Resort Room", price: 16500, capacity: 2 },
            { name: "Della Adventure Suite", price: 27000, capacity: 4 }
        ],
        availableRooms: 6,
        bestSeason: ["All Season"]
    },
    {
        title: "The Zuri Kumarakom Kerala Resort & Spa",
        description: "Set on the shores of Vembanad Lake. Features Maya Spa (one of Asia's largest wellness spas), private lagoon cottages, infinity pool, and sunset houseboat dinners.",
        image: { url: "https://images.unsplash.com/photo-1610641818989-c2051b5e2cfd?auto=format&fit=crop&w=1200&q=80", filename: "listing_zuri_kumarakom" },
        price: 16000,
        location: "V-235 A, Karottukayal",
        city: "Kumarakom",
        state: "Kerala",
        country: "India",
        category: "Resort",
        rating: 4.8,
        numReviews: 210,
        amenities: ["WiFi", "Maya Spa", "Lagoon Pool", "Lake View", "Cigar Lounge", "Ayurveda"],
        coordinates: { lat: 9.622, lng: 76.425 },
        nearbyAttractions: [{ name: "Vembanad Lake", distance: "0.0 km" }, { name: "Kumarakom Bird Sanctuary", distance: "3.0 km" }],
        travelType: ["Couples", "Luxury", "Family"],
        roomTypes: [
            { name: "Zuri Deluxe Room", price: 16000, capacity: 2 },
            { name: "Presidents Pool Villa", price: 32000, capacity: 3 }
        ],
        availableRooms: 4,
        bestSeason: ["October", "November", "December", "January", "February"]
    }
];

module.exports = sampleListings;
